### ISSUE TITLE
Tag are in line format instead of cloud format

### ISSUE THREAD

**Issue by paoesco** [sebhildebrandt/reveal.js-tagcloud-plugin#2]
Hello,

I use revealjs 3.0.0 and tagcloud 0.1.0 but when I use the plugin, the items are in line instead in cloud format 

![issue_tagcloud](https://cloud.githubusercontent.com/assets/1893985/8474517/ea3ce77a-20b0-11e5-8550-942336190e7b.jpg)

I added `{ src: 'plugin/tagcloud/tagcloud.js', async: true }` in the dependencies and added the css you mention to add some space between the tags.

My section is like this : 

``` html
<section tagcloud>
    DevOps
    PaaS
    Continuous Delivery
    Jenkins
    Framework
    Microservice
    Heroku 
    TravisCI 
    VersionEye
    Docker
    Coveralls
    Monitoring
    Logging
    SOA
</section>
```

Am I missing something ?

**Comment by paoesco** [comment]
I tried with reveal 3.1.0 and I have the same problem

Firefox 31.0 & Internet Explorer 11

**Comment by sebhildebrandt** [comment]
I will check it next week. I am sure, there will be a solution ;-)

Sebastian

**Comment by paoesco** [comment]
If you need all the code, it's here : https://github.com/paoesco/presentations/tree/master/soft_dev_made_easy

**Comment by dentinger** [comment]
I had similar issues today with the cloud not being created.  I found a work around.  If you add a single space to end of each entry you want in the tag cloud AND include the word with the space in a span then the cloud generates.  For example <pre> &lt;span&gt;foo &lt;/span&gt; </pre>instead of <pre> &lt;span&gt;foo&lt;/span&gt;  </pre> the word cloud would generate as expected.   This worked in several versions of reveal for me.   Hope this helps.

**Comment by sebhildebrandt** [comment]
Thank you Dan,

anyway, I will check the code next week (Tuesday or Wednesday) :-)

**Comment by paoesco** [comment]
Hello,

did you have a look at this issue ?
Thanks

**Comment by dentinger** [comment]
I did not get a chance to dig into why it was happening.  I ran into it and
found a quick a way to work around it.

Dan

**Comment by sebhildebrandt** [comment]
Actually, I said, I will have look at the issue. I'm sorry, but I didn't had the time. Tomorrow I will dig into the code. Ok?

Sebastian

**Comment by sebhildebrandt** [comment]
Finally: bug fixed, documentation updated (dependencies) & version update to 1.1

Sebastian

**Comment by paoesco** [comment]
Thank you very much
